model_path: unlearning_ckpt2/ft_model_10_epochs_inst_lr1e-3
model_family: llama2-7b

save_dir: ${model_path}/eval_results/ds_size${ds_size}

#dataset path for each of the 4 datasets to be evaluated
data_name: knowundo-copyright
data_path: [zjunlp/KnowUnDo, locuslab/TOFU, locuslab/TOFU, zjunlp/KnowUnDo]
split: unlearn
split_list:
  - retention
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}


question_key: [question, question, question, question]
answer_key: [answer, answer, answer, answer]

base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]

generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 300

overwrite: true
use_pretrained: false

batch_size: 8
reinitialize_weights: false

retain_result: null

